### ISSUE TITLE
Uncaught TypeError in combination with Paypal Plus FreeTextField

### ISSUE THREAD

**Issue by michael-sfx** [shyim/ShyimAttributeTransformer#8]
Hi!

I've got a very strange error:

1.) In combination with Paypal Plus Unified Installmet 2.3.0 (Ratenzahlung)
I change the following freetext field:
_frontend/paypal_unified/installments/common - link/text_
to: 

`<i class="icon--service"></i>`

And then I get the following error message at the articles Detail page:

> Fatal error: Uncaught TypeError: Argument 2 passed to ShyimAttributeTransformer\Components\AttributeTransformer::addAttribute() must be of the type string, array given, called in /www/custom/plugins/ShyimAttributeTransformer/Components/Converter.php on line 124 and defined in /www/custom/plugins/ShyimAttributeTransformer/Components/AttributeTransformer.php:59 Stack trace: #0 /www/custom/plugins/ShyimAttributeTransformer/Components/Converter.php(124): ShyimAttributeTransformer\Components\AttributeTransformer->addAttribute(Object(Shopware\Bundle\AttributeBundle\Service\ConfigurationStruct), Array) #1 /www/custom/plugins/ShyimAttributeTransformer/Components/Converter.php(63): ShyimAttributeTransformer\Components\Converter->transformAttributeFields(Array, Array, Array) #2 /www/custom/plugins/ShyimAttributeTransformer/Subscriber/TemplateSubscriber.php(118 in /www/custom/plugins/ShyimAttributeTransformer/Components/AttributeTransformer.php on line 59
>

**Comment by michael-sfx** [comment]
Ok now I see the the `"` char is causing this issue. I wonder how this interferres with the backend Attributes???
